language: ruby
rvm:
  - "2.2.0"
env: 
  - "test"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'webdriver-manager update --standalone --firefox'
install: 
  - "bundle install  